config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'questions/new'
  get 'questions/create'
  resources :surveys do
    resources :questions, only: [:new, :create]
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :position, presence: true, if: :requires_position?

  private

  # Veryfy question type
  def requires_position?
    %w[Checkbox Radio Button].include?(question.type)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  belongs_to :type
  validates :type, presence: true
  has_many :answers, dependent: :destroy
  validates :position, uniqueness: true, presence: true
  validate :validate_mutually_exclusive_selections, if: :exclusive_type?

  private

  # Verify if question is of the type checkbox or radio button
  def exclusive_type?
    %w[Checkbox Radio Button].include?(type)
  end

  def validate_mutually_exclusive_selections
    if answers.size > 5
      errors.add(:answers, "must have maximun  5 mutually exclusive selections for Checkbox or Radio Button questions")
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  validate :validate_number_of_questions
  validates :title, presence: true

  private

  def validate_number_of_questions
    if questions.size > 10
      errors.add(:questions, "must have less then 10 questions")
    end
  end
end

app/models/survey_answer.rb
class SurveyAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :survey
  belongs_to :user_answer
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = SurveyApiSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @surveys = Survey.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @question = Question.new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = Question.new(answer_params)
    @question.survey = @survey
    @question.save
  end

  private

  def answer_params
    params.require(:question).permit(:question, :type_id, :position)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.user_id = current_user.id
    @survey.save
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  private

  def survey_params
    params.require(:survey).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<ul>
  <% @surveys.each do |survey| %>
    <li><%= link_to survey.title, survey_path(survey) %></li>
  <% end %>
</ul>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/new.html.erb
<%= simple_form_for [@survey, @question] do |f| %>
  <%= f.input :question %>
  <%= f.input :type_id, collection: Type.all, label_method: :name, value_method: :id, prompt: 'Selecione o Tipo' %>
  <%= f.input :position %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create Survey", new_survey_path, class: "dropdown-item" %>
              <%# <%= link_to "My Surveys", edit_survey_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/surveys/new.html.erb
<%= form_with model: @survey do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/surveys/show.html.erb
<h1>Surveys#show</h1>
<p>Find me in app/views/surveys/show.html.erb</p>